---
title: "Erstversuch"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Zuerst die Daten laden.

```{r cars}
library(zoo)
library(TTR)

B002102.Airflow.vorher <- read.csv("C:/Users/Raoul/Desktop/MelSchlaf/Rohdaten/B002102 Airflow vorher", sep=";")
B002102.Airflow.vorher$Date = NULL
B002102.Airflow.vorher$HH = NULL
B002102.Airflow.vorher$MM = NULL
B002102.Airflow.vorher$SS = NULL 
summary(is.na(B002102.Airflow.vorher))

B002102.Airflow.vorher$Airflow.uV. = gsub("\\,", ".", B002102.Airflow.vorher$Airflow.uV.)
B002102.Airflow.vorher$Airflow.uV. = as.numeric(B002102.Airflow.vorher$Airflow.uV.)

timeSeries <- zoo(B002102.Airflow.vorher$Airflow.uV.)
plot(timeSeries)
```

## Analyse

Smoothing und Decomposition sowie Check auf NA's
```{r Smoothing, echo=FALSE, warning=TRUE}
Airvorher<-SMA(timeSeries, n=2000)
plot(Airvorher)
Airvorher.ts = zoo(Airvorher)

summary(is.na(Airvorher))

stl(Airvorher)

```

sdfsdaf externer Datenprobelauf

```{r}
library(Ecdat)

data("AirPassengers")
tsA = AirPassengers
plot(AirPassengers)
decomposed = stl(zoo(AirPassengers), s.window = 1)
summary(decomposed)
plot(decomposed)

#plot(stl(as.ts(AirPassengers)))
```

